name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^9.1.0
  gender_selection: ^1.0.0
  photo_view: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSansCondensed
      fonts:
        - asset: assets/OpenSansCondensed-Light.ttf
  assets:
    - assets/

